spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}


  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 200MB
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect

  data:
    redis:
      url: rediss://default:${REDIS_PASSWORD}@sharp-vervet-11892.upstash.io:6379
      client-type: lettuce


  mail:
    host: smtp.gmail.com
    port: 587
    username: heosejin222@gmail.com
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        debug: true

jwt:
  secret: "secret_key_secret_key_secret_key"

server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.hibernate.SQL: debug

cors:
  allowed-origins: "*"
  allowed-methods: "GET,POST,PUT,DELETE"
  allowed-headers: "Authorization,Content-Type"

google:
  maps:
    api-key: AIzaSyAuQNhpD_ilIrQ6nUv9GS7VzaPd9ZbtTEo
  cloud:
    credentials: ${GOOGLE_APPLICATION_CREDENTIALS_JSON}

